blog/urls.py
from django.urls import path

from .views import render_posts, post_detail

app_name = 'blog'

urlpatterns = [
    path('', render_posts, name="posts"),
    # sqlit3 guarda o egistra un dato en forma de numero
    path("<int:post_id>", post_detail, name="post_detail"),
]

django_portfolio/urls.py
# from django.contrib import admin
# from django.urls import path

# urlpatterns = [
#     path('admin/', admin.site.urls),
# ]


# aqui comenzo#####

# from django.contrib import admin
# from django.urls import path, include

# from django.conf.urls.static import static
# from django.conf import settings
# from portfolio import views


# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path('', views.home, name='home'),
#     path('blog/', include('blog.urls'))


# ]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


from django.contrib import admin
from django.urls import path, include
from portfolio import views

# Definición de urlpatterns para tu proyecto Django
urlpatterns = [
    path('admin/', admin.site.urls),  # Ruta para el administrador de Django
    # Ruta para la vista 'home' de la app 'portfolio'
    path('', views.home, name='home'),
    path('blog/', include('blog.urls')),  # Incluye las URLs de la app 'blog'
]

# No es necesario añadir rutas para servir archivos estáticos y multimedia en producción
# ya que se servirán directamente desde Azure Blob Storage según configuración en settings.py

blog/models.py
from django.db import models
import datetime
from django.db.models.fields import URLField


class Post(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='blog/images')
    date = models.DateField(datetime.date.today)
    title_1 = models.CharField(max_length=100, default='')
    description_1 = models.TextField(default='')
    title_2 = models.CharField(max_length=100, default='')
    description_2 = models.CharField(max_length=999, default='')
    url3 = URLField(blank=True)

portfolio/models.py
from django.db import models
# forma para importar datos
from django.db.models.fields import CharField, URLField
# forma para importar imagenes
from django.db.models.fields.files import ImageField


# Guardar los datos de mi portafolio
# Saving my porrfolio data


class Project(models.Model):
    title = CharField(max_length=100)
    description = CharField(max_length=800)
    image = ImageField(upload_to="portfolio/images/")
    url = URLField(blank=True)
    url2 = URLField(blank=True)
    video = models.FileField(
        upload_to='portfolio/videos/', blank=True, null=True)

blog/views.py
from django.shortcuts import render, get_object_or_404
# froma para importar los modelos
from .models import Post

# Esta funcion renderiza todas las publicaciones


def render_posts(request):
    # esta es la forma de proyectar desde models
    # la estructura de publicacion para verla en la pagina
    posts = Post.objects.all()
    return render(request, 'posts.html', {'posts': posts})

# Vista para renderizar una vista de detalle


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'post_detail.html', {"post": post})

portfolio/views.py
from django.shortcuts import render
from .models import Project

# Create your views here.


def home(request):
    projects = Project.objects.all()

    return render(request, 'home.html', {'projects': projects})

blog/templates/post_detail.html
{% extends 'layout.html' %}
{%block content%}

<div class="">


    <h2>{{post.title}}</h2>
    <h3 class="my-2 h5 text-muted">{{post.date|date:'F jS Y'}}</h3>

    <div class="row my-1">
        <div class="col-12">
            <img src="{{ post.image.url }}" alt="{{ post.title }}" class="img-fluid"
                style="max-width: 30%; height: auto; display: block; margin: 0 auto;">
        </div>
    </div>


    <div class="my-4">
        <h3>Description du Projet :</h3>
        <p>{{post.description|safe}}</p>
        <h3>{{post.title_1|safe}}</h3>
        <p>{{post.description_1|safe}}</p>
        <h3>{{post.title_2|safe}}</h3>
        <p>{{post.description_2|safe}}</p>

    </div>

</div>


{% endblock %}

blog/templates/posts.html
<!-- aqui editamos el tema del post -->
{%extends 'layout.html'%}
{%block content %}
<h1>Projects</h1>

{% for post in posts %}

<!-- utilizar el card car-body encierra al cotenido en tarjetas luego podemos igual especificar 
el tamaño forma o darle efectos -->
<div class="p-3">
    <div class="card card-body bg-gray">
        <div class="row">
            <!-- estas son las columnas que queremos dividir  -->
            <div class="col-3 ">
                <img src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid" />

            </div>

            <div class="col-9 text-black">
                <h2>{{post.title}}</h2>
                <h3>{{post.date}}</h3>
                <p>{{post.description|striptags|truncatechars:100 }}</p>
                <!-- con esta forma de truncatechar:100 hacemos que nuestrea description tenga 100 caratere -->

                <!-- Recuerdo esta es la forma de poner fechas automaticamente directamente desde la publicacion -->
                <!-- <p>{{post.date|date:'M d Y'|upper}}</p> -->

                <a href="{%url 'blog:post_detail' post.id %}" class="btn btn-primary">{{post.title}}</a>
                <a href="{{project.url3}}" class="btn btn-primary rounded-1 btn-2" target="__blank"
                    rel="noreferrer">Github</a>

            </div>
        </div>
    </div>


</div>

{% endfor %}{% endblock %}

portfolio/templates/home.html
{% extends 'layout.html' %}

{% block content %}

{% load static %}

<header class="row align-items-center card-project" style="background-color: #010123; ">
    <div class="col-md-3 cardstyle=" background-color: #000013;">
        <img src="{% static 'portafolio/Damian.jpg' %}" alt="" class="img-thumbnail" class="img-fluid" alt="..." />
    </div>

    <div class=" col-md-9 my-auto p-4 text-center">
        <h1> <strong>Damián Rueda</strong></h1>
        <h3>Expert en Réalité Virtuelle et technologies émergentes d'Intelligence Artificielle.
        </h3>
        <p>
            Avec une solide base en Python et un intérêt croissant pour l'apprentissage automatique, je me consacre à
            créer des
            expériences immersives en réalité virtuelle, intégrant l'intelligence artificielle pour développer des
            interactions
            intuitives et adaptatives. Ma passion est de concevoir des applications et des outils qui favorisent le
            développement
            personnel et professionnel à l'ère de l'automatisation, aidant les individus à cultiver leurs compétences et
            à s'adapter
            aux dynamiques changeantes du monde technologique.
        </p>
        <a class="btn btn-primary btn-lg rounded-0 my-3" href="{% static 'portafolio/cvo.pdf'%}" target="_blank">
            Download CV</a>
    </div>
</header>


<!-- Porfolio Section -->
<div class="row my-4 text-center">

    <h3>Mes Projets</h3>

    <p>__________________________________________________</p>

    {% for project in projects %}
    <div class="col-md-4 p-4">
        <div class="card  card-project " style="background-color:#010123;;">
            <img src=" {{project.image.url }}" class="card-img-top" />
            <!-- aqui cambiamos el color de los textos del proyecto -->

            <div class="card-body text-light  ">
                <video mx-auto controls class="img-fluid" />
                <!-- Asegúrate de que 'project.video' exista y tenga una URL válida -->
                {% if project.video %}
                <source src="{{ project.video.url }}" type="video/mp4">
                Your browser does not support the video tag.
                {% else %}
                <p>Video no disponible.</p>
                {% endif %}
                </video>

                <h2>{{ project.title }}</h2>
                <p>{{ project.description|truncatechars:100}}</p>

                {% if project.url %}
                <a href="{{project.url}}" class="btn btn-light rounded-1 btn-sm" target="__blank"
                    rel="noreferrer">github</a>

                <a href="{{project.url2}}" class="btn btn-primary rounded-1 btn-sm" target="__blank"
                    rel="noreferrer">View details</a>

                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

portfolio/templates/layout.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Django Portafolio</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{%static 'main.css'%}">
</head>
<!-- aqui cambiamos el color de los titulos alado de mi foto cv -->

<body class="text-light background-color: #000013" style="background-color: #000000;">

    {% include 'partials/navbar.html'%}

    <div class=" container p-4">
        {% block content %}
        {% endblock%}
    </div>

</body>

</html>

portfolio/templates/partials/navbar.html
{%load static%}
<!-- aqui cambiamos el color de la barra de inicio -->
<nav class="navbar navbar-expand-lg navbar-dark " style="background-color: #010123;">
    <div class="container">
        <a class="navbar-brand fw-bold fst-italic" href="/">Damián Rueda</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03"
            aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navBarNav">
            <ul class="navbar-nav ms-auto">

                <li class="nav-item ">
                    <a class="nav-link" href="{%url 'blog:posts'%}">Projets Phares</a>
                </li>
                <li class="nav-item d-flex align-items-center">
                    <a class="btn btn-primary btn-sm " href="{% static 'portafolio/cvo.pdf' %}" target="_blank">Download
                        CV</a>
                </li>

                <ul>
        </div>
    </div>
</nav>